package com.mimedia.poc.jade.agent.form;

import javax.swing.*;
import java.awt.*;

public class ProcessTaskForm {
    private JPanel mainPanel;

    private JButton processTasksButton;

    public JPanel getMainPanel() {
        return mainPanel;
    }

    public JButton getProcessTasksButton() {
        return processTasksButton;
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(2, 2, new Insets(0, 0, 0, 0), -1, -1));
        processTasksButton = new JButton();
        processTasksButton.setText("Process Tasks");
        mainPanel.add(processTasksButton,
                      new com.intellij.uiDesigner.core.GridConstraints(0,
                                                                       0,
                                                                       1,
                                                                       1,
                                                                       com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER,
                                                                       com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL,
                                                                       com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK
                                                                       | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW,
                                                                       com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED,
                                                                       null,
                                                                       null,
                                                                       null,
                                                                       0,
                                                                       false));
        final com.intellij.uiDesigner.core.Spacer spacer1 = new com.intellij.uiDesigner.core.Spacer();
        mainPanel.add(spacer1,
                      new com.intellij.uiDesigner.core.GridConstraints(0,
                                                                       1,
                                                                       1,
                                                                       1,
                                                                       com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER,
                                                                       com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL,
                                                                       com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW,
                                                                       1,
                                                                       null,
                                                                       null,
                                                                       null,
                                                                       0,
                                                                       false));
        final com.intellij.uiDesigner.core.Spacer spacer2 = new com.intellij.uiDesigner.core.Spacer();
        mainPanel.add(spacer2,
                      new com.intellij.uiDesigner.core.GridConstraints(1,
                                                                       0,
                                                                       1,
                                                                       1,
                                                                       com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER,
                                                                       com.intellij.uiDesigner.core.GridConstraints.FILL_VERTICAL,
                                                                       1,
                                                                       com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW,
                                                                       null,
                                                                       null,
                                                                       null,
                                                                       0,
                                                                       false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }
}
